### ISSUE TITLE
[doc issue] Links not working

### ISSUE THREAD

**Issue by AjitKP91** [SAP-docs/sapui5#101]
### Issue description

For more information, see [Managing Variants](https://sapui5.hana.ondemand.com/sdk/topic/8ce658e05498466d9a74823b94e840ac.html) and [Enabling Variant Management on the Object Page](https://sapui5.hana.ondemand.com/sdk/topic/f26d42bea11c4deda82c7a2e00c9bc05.html). 

**Links are not working in above line in the page [Enabel Personalization](https://sapui5.hana.ondemand.com/sdk/#/topic/3e2b4d212b66481a829ccef1dc0ca16b)** 

### Feedback Type (Optional)

linking

### Page Title on SAP Help Portal (prefilled)

Enabling Table Personalization

### Page URL on SAP Help Portal (prefilled)

https://sapui5.hana.ondemand.com/sdk/#/topic/3e2b4d212b66481a829ccef1dc0ca16b

**Comment by KvM2** [comment]
Hi @AjitKP91 , thanks for your contribution . We appreciate it and will look into this.

**Comment by didzvein** [comment]
Hello @AjitKP91, thanks for spotting this! We've identified the issue, and we're looking for a solution.

Meanwhile, the links still should work if you click them directly, not with right click and open in new tab. If this does not work, either, please do let us know!

**Comment by OlMue** [comment]
Hi @AjitKP91, a fix is on its way, so I'm closing the issue. Thanks for your contribution!
