### ISSUE TITLE
Documentation missing for important `sap-ui-xx-viewCache` url parameter

### ISSUE THREAD

**Issue by nicoschoenteich** [SAP-docs/sapui5#102]
### Issue description

Hi there,

I noticed that the `sap-ui-xx-viewCache` url parameter is not documented (at least not in this camel case form), although it is being used in a lot of samples and templates. While the `sap-ui-xx-view-cache` (in kebab case) parameter is documented (and seems to be doing the same thing), it is unfortunate that there are no useful hits when searching for `sap-ui-xx-viewCache` in the global search - despite this being one of the most used url parameters, especially during development. To further improve the search, I would also suggest to include the actual url parameters in their long form somewhere on the page (`sap-ui-xx-viewCache`), instead of just the short forms (`xx-viewCache`).

Best, Nico

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Deprecated and Experimental Configuration Options

### Page URL on SAP Help Portal (prefilled)

https://sapui5.hana.ondemand.com/#/topic/b474a712ca364d40a1b0a804baf2d734

**Comment by BorisDafov** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by KlattG** [comment]
Hi @nicoschoenteich  , thank you for your patience. We understand that an explanation of the switch from camel-case to kebab-case notation for the config options is required for our documentation. We are working on your concern and will be updating the documentation soon.

**Comment by KlattG** [comment]
Hi @nicoschoenteich , we have added a note explaining the new casing convention and are currently busy harmonizing the casing in our sample code. I expect our documentation to use consistent casing for the config parameters as of the next release.
Kind regards
Günter
