### ISSUE TITLE
[doc issue] 

### ISSUE THREAD

**Issue by biscimus** [SAP-docs/sapui5#103]
### Issue description

The hyperlinks in the [manifest.json documentation](https://github.com/SAP-docs/sapui5/blob/main/docs/04_Essentials/descriptor-for-applications-components-and-libraries-manifest-json-be0cf40.md) are all wrong!!

### Feedback Type (Optional)

linking

**Comment by BorisDafov** [comment]
Hi [biscimus](https://github.com/biscimus), thanks for your feedback. I have now checked several hyperlinks in the [manifest.json documentation](https://github.com/SAP-docs/sapui5/blob/main/docs/04_Essentials/descriptor-for-applications-components-and-libraries-manifest-json-be0cf40.md) but couldn't find any wrong. Could you please give an example? Thank you!
