### ISSUE TITLE
[doc issue] Why is Asynchronous Loading both deprecated and recommended?

### ISSUE THREAD

**Issue by ziyang-works** [SAP-docs/sapui5#104]
### Issue description

I'm new to UI5 and am currently deciding if I should set `data-sap-ui-async="true"` for my new UI5 project.

However, I'm finding this option listed as deprecated on [Deprecated and Experimental Configuration Options](https://sapui5.hana.ondemand.com/sdk/#/topic/b474a712ca364d40a1b0a804baf2d734) while recommended at [Use Asynchronous Loading](https://sapui5.hana.ondemand.com/sdk/#/topic/676b636446c94eada183b1218a824717).
<img width="847" alt="image" src="https://github.com/SAP-docs/sapui5/assets/152387247/2e9c2577-b9c0-41b2-9c39-651ae0adb675">

<img width="846" alt="image" src="https://github.com/SAP-docs/sapui5/assets/152387247/5c4a1547-1907-4ccc-9e56-daed2b896910">

I am a bit confused now. If the option is deprecated, does it mean it could be removed in the future and I should not use it for new projects? If so, why is the option still listed as recommended?

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Deprecated and Experimental Configuration Options

### Page URL on SAP Help Portal (prefilled)

https://sapui5.hana.ondemand.com/sdk/#/topic/b474a712ca364d40a1b0a804baf2d734

**Comment by KvM2** [comment]
Hi @ziyang-works , thanks for your contribution . We appreciate it and will look into this.

**Comment by KlattG** [comment]
Hi @ziyang-works  , thank you for your patience. We understand that a more accurate listing of deprecated config parameters is required for our documentation. We are working on your concern and will be updating the documentation soon.

**Comment by KlattG** [comment]
Classification of the `async` option will be fixed in one of the next patch sets / next release.

**Comment by ziyang-works** [comment]
https://people.wdf.sap.corp/profiles/I557164
