### ISSUE TITLE
[doc issue] Inconsistent casing for configuration options in doc

### ISSUE THREAD

**Issue by ziyang-works** [SAP-docs/sapui5#105]
### Issue description

I was browsing through sample code from the documents and wanted to find clarification for some configuration options used for UI5 loading.
However, I was unable to find some configuration options used in sample code from [Configuration Options and URL Parameters](https://sapui5.hana.ondemand.com/sdk/#/topic/91f2d03b6f4d1014b6dd926db0e91070).

Upon further investigation, I realize the issue was inconsistent casing. The documentation presented sample code lines with `camelCase` or `lowercase` for options, whereas [Configuration Options and URL Parameters](https://sapui5.hana.ondemand.com/sdk/#/topic/91f2d03b6f4d1014b6dd926db0e91070) exclusively showcased `kebab-case`.

I find it would be easier for me (and fellow UI5 beginners) if all sample code in the documentation uses the same casing convention for configuration options.

Example samples not using `kebab-case`:

[Step 1: Ready...](https://sapui5.hana.ondemand.com/sdk/#/topic/851bde42e4e1410c96abbe402fa9128c):

```diff
	<script id="sap-ui-bootstrap"
		src="https://sdk.openui5.org/resources/sap-ui-core.js"
		data-sap-ui-theme="sap_belize"
		data-sap-ui-libs="sap.m"
+		data-sap-ui-resourceroots='{"Quickstart": "./"}'
+		data-sap-ui-onInit="module:Quickstart/index"
+		data-sap-ui-compatVersion="edge"
		data-sap-ui-async="true">
	</script>
```

We can find more relevant pages by searching for `resourcingroots`, `onInit`, or `compatVersion` in doc.

Example:
<img width="1503" alt="image" src="https://github.com/SAP-docs/sapui5/assets/152387247/496b8bfd-db55-4c96-970f-c5ba92764aec">

### Feedback Type (Optional)

examples or samples

### Page Title on SAP Help Portal (prefilled)

Configuration Options and URL Parameters

### Page URL on SAP Help Portal (prefilled)

https://sapui5.hana.ondemand.com/sdk/#/topic/91f2d03b6f4d1014b6dd926db0e91070

**Comment by KvM2** [comment]
Hi @ziyang-works , thanks for your contribution . We appreciate it and will look into this.

**Comment by KlattG** [comment]
Hi @ziyang-works , we have added a note explaining the new casing convention and are currently busy harmonizing the casing in our sample code. I expect the issue to be fixed in the next release.
Kind regards
Günter
