### ISSUE TITLE
[doc issue] quickstart tutorial doc code issue

### ISSUE THREAD

**Issue by Hsin-Lan** [SAP-docs/sapui5#108]
### Issue description

Hello Team,

I was following the tutorial "Quickstart" and got unexpected results at Step 2: Steady...

I can't get expected inline button and interactive Message Toast if I followed the code mentioned on the page. However, I changed the code in webapp/index.js and webapp/App.view.xml, then it worked fine.

Affected code:
1. webapp/index.js
line 6
tutorial version: XMLView.create({viewName: "Quickstart.App" ......
my version: XMLView.create({viewName: "ui5.quickstart.App"} ......

2. webapp/App.view.xml
line 2
tutorial version: 	controllerName="Quickstart.App"
my version: controllerName="ui5.quickstart.App"

After changing the code, I'm able to successfully run the program and get the button and subsequent Message Toast.

### Feedback Type (Optional)

spelling or grammar

### Page URL on SAP Help Portal (prefilled)

https://ui5.sap.com/#/topic/128214a9b2754b15aec5e365780b03fd

**Comment by flovogt** [comment]
@Hsin-Lan Thanks for opening this issue. @KlattG/@OlMue lets sync on this to get this fixed.

**Comment by KlattG** [comment]
@Hsin-Lan The issue will be fixed in the next release.

**Comment by flovogt** [comment]
Fixed with https://github.com/SAP/openui5/commit/f46e7a797671249cf286131b7c792d4a4746af55 and https://github.com/SAP/openui5/commit/f0f5ceefa302a2cb3da1613a202380a0954cc23d.
