### ISSUE TITLE
[doc issue] Missing documentation to Event Buses

### ISSUE THREAD

**Issue by biscimus** [SAP-docs/sapui5#109]
### Missing documentation to Event Buses

Hello Documentation Team,

Recently, I faced an issue trying to access controllers of child views inserted in the parent view. The concept of event buses really helped to reduce lines of code and to make the entire inter-controller-communication easier (in case there are better ways to solve this problem, please let me know). However, the event bus feature was overlooked by our team for quite some time, since there weren't any documentation pages referring to the feature, but only a single API reference page instead. There are a couple documentation pages describing how to incorporate child views using multiple targets, but no description how these child controllers should interact with each other & communicate information. Event buses also come in handy when generally dealing with publishing custom events, which is why I'm proposing a documentation page for the event bus feature.

### Feedback Type (Optional)

None

**Comment by KvM2** [comment]
@biscimus, Thanks for your contribution - we appreciate it. Would you mind pointing out to me any related documentation and where you miss such an event bus-related documentation? Thanks!

**Comment by boghyon** [comment]
@biscimus Would it be helpful to have something like https://stackoverflow.com/a/46186706/5846045 in the documentation?

**Comment by biscimus** [comment]
@boghyon Yes something like that would be very nice!

**Comment by biscimus** [comment]
@Thodd Thank you for your detailed input. If the event bus is that much of a sensitive topic, isn't that even another reason to add a documentation regarding this feature?

**Comment by KlattG** [comment]
@biscimus After lengthy discussion with our developers, we concluded that providing additional documentation on the event bus feature is neither necessary nor prudent at this point. We promise, however, to keep an eye on the issue and inform you if anything changes.
