### ISSUE TITLE
Fiori Element Add column to table missing crucial information

### ISSUE THREAD

**Issue by NSXBLUE** [SAP-docs/sapui5#110]
### Issue description

The documentation of extending Fiori Element responsive table is missing the name of the fragment files you are supposed to create. It mentions you need two extensions, then it provides code for the two extensions, but it only specifies the file name for the second code snippet. It took me hours to find out what I was doing wrong.

[https://sapui5.hana.ondemand.com/#/topic/28e95702b5854b938ac51c4bc2d078ab.html](url)

The first code snippet needs to mention create a file: **webapp/ext/fragments/ListReportResponsiveTableCells.fragment.xml**

The equivalent doc for grit table extension is also missing this crucial piece of information.

Also, the documentation fails to indicate how to deploy this FE extension and run it in Fiori Launchpad. How do you ensure your new columns will be available when users click on the original app's tile? 
I'm still stuck on that, trying to find other online sources to explain the process. 

Thanks

### Feedback Type (Optional)

examples or samples

### Page Title on SAP Help Portal (prefilled)

Example: Adding Columns to a Responsive Table in the List Report

### Page URL on SAP Help Portal (prefilled)

https://sapui5.hana.ondemand.com/#/topic/28e95702b5854b938ac51c4bc2d078ab.html

**Comment by OlMue** [comment]
Hi @NSXBLUE, thanks for your contribution! We'll look into it and get back to you.

**Comment by mishuagrawal** [comment]
Hello @NSXBLUE, we are working on your concern and will share an update here soon. Kindly bear with us while we try to resolve this. Thank you!

**Comment by anjan-poonacha** [comment]
@mishuagrawal I could add the following code in [my test repository](https://github.tools.sap/FIORI-STTA/stta.prod.man.typescript). As a result a custom column is visible.
 

```xml
<!-- Generate the custom column fragment -->
<!-- fragments/ResponsiveTableColumns.fragment.xml -->
<core:FragmentDefinition xmlns:core="sap.ui.core" xmlns="sap.m">
    <!--Column 1 Header-->
    <Column id="textColumn">
        <Text text="Extension Column"/>
        <customData>
            <core:CustomData key="p13nData" value="\{'columnKey': 'CustomColumn1', 'leadingProperty': 'Depth', 'columnIndex': '101'}"/>
        </customData>
    </Column>
</core:FragmentDefinition>

```

```xml
<!-- Generate custom cell fragment -->
<!-- fragments/ResponsiveTableCells.fragment.xml -->

<core:FragmentDefinition xmlns:core="sap.ui.core" 
    xmlns="sap.m">
	<!--Column 1 Cell-->
	<Text text="Breakout Column"></Text>
</core:FragmentDefinition>

```


```jsonc
// Add extension settings to the manifest
// manifest.json

"sap.ui.viewExtensions": {
	"sap.suite.ui.generic.template.ListReport.view.ListReport": {
		"ResponsiveTableColumnsExtension|STTA_C_MP_Product": {
			"className": "sap.ui.core.Fragment",
			"fragmentName": "stta.prod.man.typescript.ext.fragments.ResponsiveTableColumns",
			"type": "XML"
		},
		"ResponsiveTableCellsExtension|STTA_C_MP_Product": {
			"className": "sap.ui.core.Fragment",
			"fragmentName": "stta.prod.man.typescript.ext.fragments.ResponsiveTableCells",
			"type": "XML"
		}
	}
}

```
![image](https://github.com/SAP-docs/sapui5/assets/113531828/98d5da03-b3df-4600-8923-b7a5cc317e81)

**Comment by mishuagrawal** [comment]
Hello @NSXBLUE,

Thank you for your patience. As you can see, our dev has reviewed your concern and they have confirmed that they were able to add the mentioned code in the test repository and were also able to create a custom column. If you are still facing issues, please let us know.

Also, regarding the deployment of FE extension to SAP Fiori launchpad, kindly check the Deploying an Application (https://help.sap.com/docs/SAP_FIORI_tools/17d50220bcd848aa854c9c182d65b699/1b7a3be8d99c45aead90528ef472af37.html) documentation. This document is for SAP Fiori Tools. 

Please let us know if this resolves your query. 

Thanks and regards,
Mishu Agrawal

**Comment by mishuagrawal** [comment]
Hello @NSXBLUE,

We are waiting to hear from you. Kindly write back to us and let us know how we can help you further in this regard.

Best,
Mishu Agrawal

**Comment by NSXBLUE** [comment]
I guess I wasn't clear about the issue, sorry. What I'm saying is that there are two pieces of code for two fragments. One of them (the second one) clearly specifies the file name and location it needs to be saved in: /webapp/ext/fragments/ListReportResponsiveTableColumns.fragment.xml.  But the first one does not.

Please see screenshot below. What is the name and location of the first fragment?

![image](https://github.com/SAP-docs/sapui5/assets/32580773/c55d494d-3362-46f7-9056-a6ad92e5c802)

**Comment by mishuagrawal** [comment]
Hello @NSXBLUE,

Thank you for writing back to us. This helps. We are now working on your concerns and will get back to you soon.

Thanks and regards,
Mishu Agrawal

**Comment by cfg74** [comment]
Hi @NSXBLUE I would like to address your deployment question. When extensions are made to the app in your development environment, then they are part of the app's code, and will be deployed when you redeploy the now modified app. The documentation you are following assumes that the app is your own custom developed application where you own the lifecycle.

In case you want to extend an application which was delivered to you (like a SAP provided app), you have to create an adaptation project which is a different process with also partly different tooling. Please refer to https://sapui5.hana.ondemand.com/#/topic/52fc48b479314d0688be24f699778c47

**Comment by mishuagrawal** [comment]
Hello @NSXBLUE, 

Thank you for your patience. I apologies that it took us some time to resolve your concern.

We have now enhanced the document. We have mentioned the file name and location for both the code fragments now. Regarding your deployment query, my colleagues @cfg74 has responded to it. I hope this resolves your concern. 

If yes, I kindly request you to close this issue. If you have any concerns, you can reach out to us.

Thanks and regards,
Mishu Agrawal

**Comment by NSXBLUE** [comment]
Thanks for your help. 
Closing the issue.
