### ISSUE TITLE
Broken link in Mock Server page

### ISSUE THREAD

**Issue by esajic-ct** [SAP-docs/sapui5#111]
The link to the CAP documentation for OData v4 mocking shown below isn't working. Should it be e.g. https://cap.cloud.sap/docs/guides/using-services#local-mocking ?

https://github.com/SAP-docs/sapui5/blob/67027c864db9f46eb568d1c0d14044eb7979ee00/docs/04_Essentials/mock-server-69d3cbd.md?plain=1#L28

**Comment by OlMue** [comment]
Hi @esajic-ct, thanks for your contribution, I'll look into it.

**Comment by OlMue** [comment]
Hi again, I have corrected the link. The new version of the documentation page will be available with the next UI5 version. Thanks! :-)
