### ISSUE TITLE
Linked openSAP course has been retired [doc issue] 

### ISSUE THREAD

**Issue by huulanka** [SAP-docs/sapui5#115]
### Issue description

[The documentation](https://sapui5.hana.ondemand.com/sdk/#/topic/8b49fc198bf04b2d9800fc37fecbb218) refers to an [openSAP course](https://open.sap.com/courses/ui51/items/909S9N2WXlFOzzRfv7RDE) which is deprecated and no longer available.
![image](https://github.com/SAP-docs/sapui5/assets/86191176/dcad7718-1c34-4e1c-a7a6-8f452fbc8838)
![image](https://github.com/SAP-docs/sapui5/assets/86191176/fb037d26-1284-49cf-80e6-2f5254dd17b5)

### Feedback Type (Optional)

linking

### Page Title on SAP Help Portal (prefilled)

Get Started: Setup, Tutorials, and Demo Apps

### Page URL on SAP Help Portal (prefilled)

https://sapui5.hana.ondemand.com/sdk/#/topic/8b49fc198bf04b2d9800fc37fecbb218

**Comment by huulanka** [comment]
https://people.sap.com/abauer

**Comment by OlMue** [comment]
Hi @huulanka, good catch, thanks for letting us know! I'll remove this immediately, and it will be gone in the next version (1.123).
