### ISSUE TITLE
Finding the Right Key for the Anchor: Explain how to setup the placement for custom sections/subsections

### ISSUE THREAD

**Issue by PierreFritsch** [SAP-docs/sapui5#117]
### Issue description

The page [Finding the Right Key for the Anchor](https://sapui5.hana.ondemand.com/sdk/#/topic/6ffb084e6d8247d1863005c14e8d5894.html) ([finding-the-right-key-for-the-anchor-6ffb084.md](https://github.com/SAP-docs/sapui5/blob/main/docs/06_SAP_Fiori_Elements/finding-the-right-key-for-the-anchor-6ffb084.md)) explains:

- How to Find Anchors for the Header Facet
- How to Find Anchors for the Header Facet Field
- How to Find Anchors for the Table Column

I would expect that it also explains how to find anchors for [custom subsections](https://sapui5.hana.ondemand.com/sdk/#/topic/92ad9968e41748aeb74971f7a08a91c8.html).

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Finding the Right Key for the Anchor

**Comment by OlMue** [comment]
Hi @PierreFritsch, thanks for your contribution! We'll look into it and will get back to you.

**Comment by JannaLisa** [comment]
Hello @PierreFritsch ,
I'm checking with one of our developers how to best close this gap.
Please be patient, we're already investigating!

**Comment by JannaLisa** [comment]
just wanted to let you know there are still discussions going on, so it will take some more time before we can provide an update here. But we're working on it, @PierreFritsch.

**Comment by DivyaVD** [comment]
Hello @PierreFritsch, 

Thank you for your patience regarding this matter. I sincerely apologize for the delay from our end.
As @JannaLisa  mentioned earlier, our developers and the PO are actively working on addressing the issue. However, it will take some additional time to fully resolve and close this gap.
We truly appreciate your understanding and will keep you updated as we make progress. Please feel free to reach out if you have any further questions or concerns in the meantime.

**Comment by DivyaVD** [comment]
Hello @PierreFritsch, 

I have updated the topic **Finding the Right Key for the Anchor** with the information about 'How to Find Anchors for the Section or Subsection'. The changes will be visible with the release 1.132. 
Thank you for your patience.
