### ISSUE TITLE
Horizon theme missing in `Theme Parameter Toolbox`

### ISSUE THREAD

**Issue by nicoschoenteich** [SAP-docs/sapui5#12]
Hi team,

I believe the `sap_horizon` and `sap_horizon_dark` themes are missing in the `Theme Parameter Toolbox`. They are available for quite a while now so I think they should be added there.

Looking forward to hearing back from you!

**Comment by DavidMitreski5** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by KvM2** [comment]
Hello @nicoschoenteich , since this is not something in the documentation, I had to discuss this with development. We will look into this further and get back to you. Thanks for your patience!

**Comment by KvM2** [comment]
We are still working on this - it will take some more time. Thanks for your patience!

**Comment by KvM2** [comment]
Hi @nicoschoenteich, all available themes will now be visible in the Theme Parameter Toolbox under https://ui5.sap.com/test-resources/sap/m/demokit/theming/webapp/index.html in 1.113. Thanks for your patience!
