### ISSUE TITLE
Adaption of Fiori Elements v4 App

### ISSUE THREAD

**Issue by mzinnoecker** [SAP-docs/sapui5#120]
### Issue description

Due to more and more usage of v4 fiori elements in pre-delivered apps there is - of course - more and more demand for adapting the apps and e.g. extending with new Nodes/additional features to meet customer requirements.
I do not know wether you are interested in this kind of discussions, or this is the right place: if not, please just give me a short hint.

In the linked article we can finde the hint 

> This topic is currently only applicable to SAP Fiori elements for OData V2.

Would you mind adding details how adding subpages in v4 apps can be done?
Are this features currently not supported or "just" undocumented?

PS let me also provide an example... The app F3893 "Manage Sales Order V2" is a fiori elements v4 app

Thanks,
Michael

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Extending the Delivered Apps Manifest Using an Adaptation Project

### Page URL on SAP Help Portal (prefilled)

https://sapui5.hana.ondemand.com/sdk/#/topic/a2b24a69baef4b91af2293ccc6b5871f

**Comment by OlMue** [comment]
Hi @mzinnoecker, thanks for your contribution! We'll take a look and get back to you.

**Comment by mishuagrawal** [comment]
Hello @mzinnoecker,

Thank you for reaching out to us. Please know that we are already researching the concern with our concerned colleagues. I will get back to you as soon as I have an update.

**Comment by mishuagrawal** [comment]
Hello @mzinnoecker,

Thank you for your patience. We are working on your concern and share an update soon. 

Thanks and regards,
Mishu Agrawal

**Comment by mishuagrawal** [comment]
Hello @mzinnoecker,

Thank you for your patience. 

We understand that you required further information on how to extend delivered apps for V4. You can use the following document to get those details:

https://ui5.sap.com/#/topic/59bfd317ed5d4af3b490abbe7a9731d8

We have also updated our V2 specific document. It now has a link of the above mentioned topic to redirect you to the V4 related information. The changes should reflect once we publish for our next release. 

In the meantime, please check the mentioned topic and let us know if this resolves your concern.

Best regards,
Mishu Agrawal

**Comment by mzinnoecker** [comment]
Hello @mishuagrawal ,
thanks for the detailed answer and sorry for the late response.
I had a deep look into the provided documentation and also again on the general documentation for adaption.

I can see that you added the link to v4 adaption, but unfortunately... I cannot find documentation how to add subsections for extended nodes... For V2 you provide the information in https://ui5.sap.com/#/topic/a2b24a69baef4b91af2293ccc6b5871f, section "Adding a New Subobject Page for the Newly Extended Node".
But the feature map for v4 do not include the possibility for adding subsections via manifest extension (in an adaption project). Also i cannot find information about this specific requirement in any v4 related documentation. Also i checked the fiori tools adaption and i cannot find such a functionality for a v4 app.

That was the main reason for this github issue.
Maybe you can bring some light into this?

Thanks and Best Regards,
Michael

**Comment by mishuagrawal** [comment]
Hello @mzinnoecker,

Thanks for reaching out to us again. I apologies for the inconvenience. Please know that we are working on your concern and will get back to you soon. Thank you for your patience.

Best Regards,
Mishu Agrawal

**Comment by mishuagrawal** [comment]
Hello @mzinnoecker,

We’re really sorry as we are unable to provide a resolution to this concern right now. We have internally discussed this with our team and have made them aware of the situation. For now, we're closing this issue. Please rest assured that we will keep working on adapting this documentation and tackle the gap that you've identified. If we have updates or questions for you, we will reopen this conversation.

Thanks and regards,
Mishu Agrawal
