### ISSUE TITLE
The dialog is new but not highlighted as such

### ISSUE THREAD

**Issue by o-liver** [SAP-docs/sapui5#127]
[In the code changes for the webapp/controller/HelloPanel.controller.ts](https://ui5.sap.com/#/topic/4b2e306f4bcd4777b068e5a99e007e85) the `private dialog: Dialog;` statement is **not** highlighted in yellow, even though it is a new change in regards to the previous step.

https://github.com/SAP-docs/sapui5/blame/e91c998501a959ac766536e81a537ea6916bec80/docs/03_Get-Started/step-16-dialogs-and-fragments-typescript-4b2e306.md#L75

**Comment by KlattG** [comment]
Fixed from UI5 1.125
