### ISSUE TITLE
The sap help disclaimer blocks opening the icon explorer

### ISSUE THREAD

**Issue by o-liver** [SAP-docs/sapui5#128]
When I try to open the link to the Icon Explorer I get directed [here](https://help.sap.com/docs/link-disclaimer?site=test-resources%2Fsap%2Fm%2Fdemokit%2FiconExplorer%2Fwebapp%2Findex.html) to a help.sap.com site that reads:

"Sorry, this page cannot be accessed from our servers" instead of [the expected Icon Explorer
](https://ui5.sap.com/test-resources/sap/m/demokit/iconExplorer/webapp/index.html)

This is the case for step 18 of the walkthrough for both JS and [TS](https://github.com/SAP-docs/sapui5/blob/e91c998501a959ac766536e81a537ea6916bec80/docs/03_Get-Started/step-18-icons-typescript-49b1ac6.md?plain=1#L66C62-L66C141)

**Comment by KvM2** [comment]
Hi @o-liver, thanks for your contribution! We'll look into it and will get back to you.

**Comment by o-liver** [comment]
843769

**Comment by KlattG** [comment]
This will be fixed from UI5 1.125
