### ISSUE TITLE
MockServer cannot be instantiated in ts as it is an abstract class

### ISSUE THREAD

**Issue by o-liver** [SAP-docs/sapui5#131]
When copying this code 
https://github.com/SAP-docs/sapui5/blob/e91c998501a959ac766536e81a537ea6916bec80/docs/03_Get-Started/step-26-mock-server-configuration-typescript-3e1c64f.md?plain=1#L157-L159
 I get the following error:

>Cannot create an instance of an abstract class.ts(2511)

How can this be done instead?

**Comment by o-liver** [comment]
843769

**Comment by KvM2** [comment]
Hi @o-liver, thanks for your contribution! We'll look into it and will get back to you.

**Comment by KlattG** [comment]
Fixed as of the next release.
