### ISSUE TITLE
UriParameters is deprecated

### ISSUE THREAD

**Issue by o-liver** [SAP-docs/sapui5#132]
https://github.com/SAP-docs/sapui5/blob/e91c998501a959ac766536e81a537ea6916bec80/docs/03_Get-Started/step-26-mock-server-configuration-typescript-3e1c64f.md?plain=1#L161

Here the documentation is referring to a deprecated UriParameters function. What can be used here instead?

**Comment by KvM2** [comment]
Hi @o-liver, thanks for your contribution! We'll look into it and will get back to you.

**Comment by KlattG** [comment]
Fixed with UI5 1.126
