### ISSUE TITLE
Manifest Parameters for Cards returns 404

### ISSUE THREAD

**Issue by MikkelJ** [SAP-docs/sapui5#134]
### Issue description

UI Integration Cards  -> Overview-> Parameters leads to a 404 page. 

https://ui5.sap.com/test-resources/sap/ui/integration/demokit/cardExplorer/webapp/index.html#/learn/features/manifestParameters

### Feedback Type (Optional)

None

**Comment by KvM2** [comment]
Hi @MikkelJ , thanks for your contribution! We'll look into it and will get back to you.

**Comment by LilyanaOviPe** [comment]
Hi @MikkelJ. Thanks for your contribution and apologies for taking longer to look into your issue. I've checked the link you reported and opened a support ticket to the respective team to correct it. 

Best regards,
Lilyana

**Comment by kskondov** [comment]
Hello @MikkelJ ,   this issue is now fixed in the master branch
