### ISSUE TITLE
Missing explanation & CDS reference

### ISSUE THREAD

**Issue by sonjadeissenboeck** [SAP-docs/sapui5#138]
### Issue description

Would it be possible to update [this documentation](https://github.com/SAP-docs/sapui5/blob/main/docs/06_SAP_Fiori_Elements/disabling-the-editing-status-filter-8eb695a.md) with how to achieve this with cds annotations? 
Thanks in advance!

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Disabling the Editing Status Filter

### Page URL on SAP Help Portal (prefilled)

https://sapui5.hana.ondemand.com/sdk/#/topic/8eb695ac473b4ab0a726e4021ce35cf4

**Comment by OlMue** [comment]
Hi @sonjadeissenboeck thanks for your suggestion! We'll take a look and will get back to you.

**Comment by mishuagrawal** [comment]
Hello @sonjadeissenboeck,

Please know that we are working on updating the document and will share an update with you as soon as we can. Thank you for your patience. 

Thanks and regards,
Mishu Agrawal

**Comment by mishuagrawal** [comment]
Hello @sonjadeissenboeck,

Please know that I have updated the document now with the CDS annotation. You will be able to see the changes with our upcoming release. Please let us know if we can go ahead and close this issue now.

Thanks and regards,
Mishu Agrawal

**Comment by sonjadeissenboeck** [comment]
Hi Mishu,

Haven't seen the updated documentation yet. I just found [this help page](https://help.sap.com/docs/SAPUI5/96880755e4e64fcd96c12694f430fece/8eb695ac473b4ab0a726e4021ce35cf4.html?locale=en-US&state=DRAFT&q=Disabling%20the%20Editing%20Status%20Filter), however, the here mentioned CSD annotations didn't show any effect in my application.

Best regards
Sonja

**Comment by sonjadeissenboeck** [comment]
> Thank you for your valuable feedback contribution, @sonjadeissenboeck! So that we can [recognize your contribution in the SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please check your SAP Community user ID (this is a number) in your [personal settings page](https://community.sap.com/t5/user/myprofilepage/tab/personal-profile) and share it with us in a reply to this comment. Make sure you just include the number in the reply.
> 
> Your user ID is displayed as follows:
> 
> **Change display name for User ID N**
> 
> where N is your user ID. For example, [53 is the user ID of the user 'qmacro'](https://community.sap.com/t5/user/viewprofilepage/user-id/53).
> 
> Please note that we are currently refactoring our profile and badge system on the SAP Community, and will start assigning badges again when that's complete.

User ID 129909

**Comment by vinayhospete** [comment]
Hi @sonjadeissenboeck 

Did you try with CAP or ABAP CDS ?

**Comment by sonjadeissenboeck** [comment]
Hi Vinay,

I tried it with CAP CDS.
![image](https://github.com/user-attachments/assets/0713091f-50f3-4fb9-9327-6cdfa0ee7dff)
I actually get the error "The path DraftAdministrativeData does not exist", even though it exists as Navigation property in the corresponding entity (News)
![image](https://github.com/user-attachments/assets/81aa504c-9e5f-4ad9-a799-a8870423af72)

Best regards
Sonja

**Comment by vinayhospete** [comment]
Hi @sonjadeissenboeck 

Could you please test it with latest UI5 version. This feature is recently supported in V4.

1) Please change src="https://sapui5.hana.ondemand.com/1.126.0/resources/sap-ui-core.js" in your project
 capproject/app/<yourfioriapp>/webapp/index.html.

2) Ignore the error "The path DraftAdministrativeData does not exist" for now.

3) Try with below snippet and do not forget to clear cache in browser.

`annotate service.News with @(
 Capabilities: {
    NavigationRestrictions : {
        $Type : 'Capabilities.NavigationRestrictionsType',
        RestrictedProperties : [
            {
                $Type : 'Capabilities.NavigationPropertyRestriction',
                NavigationProperty : DraftAdministrativeData,
                FilterRestrictions : {
                    $Type : 'Capabilities.FilterRestrictionsType',
                    Filterable : false,
                },
            },
        ],
    },
});`

Let us know if this works for you.

Best regards,
Vinay

**Comment by sonjadeissenboeck** [comment]
Hi Vinay,

Indeed, hardcoding the newest 1.126.0 release solved the problem. 
Thanks for your support.

Best regards,
Sonja

**Comment by mishuagrawal** [comment]
Hello @sonjadeissenboeck,

We are glad that your concern is resolved. I have gone ahead and updated the XML as well as CAP CDS annotation in the document as well. The changes will reflect with our next release. Please let me know if your concern is now resolved and if I can go ahead and close this issue. 

Thanks and regards,
Mishu Agrawal

**Comment by mishuagrawal** [comment]
Hello @sonjadeissenboeck,

We had updated the document last week itself. The changes will reflect with our upcoming release. Please confirm if your concern is resolved and if we can close this issue.

Thanks and regards,
Mishu Agrawal

**Comment by mishuagrawal** [comment]
Hello @sonjadeissenboeck,

We had updated the document last week itself. The changes will reflect with our upcoming release. Please confirm if your concern is resolved and if we can close this issue.

Thanks and regards,
Mishu Agrawal

**Comment by mishuagrawal** [comment]
Hello @sonjadeissenboeck ,

Please know that the document has been updated and is now reflecting the change. You can check the documentation here:

https://ui5.sap.com/1.127.0/#/topic/8eb695ac473b4ab0a726e4021ce35cf4

Please confirm if we can go ahead and close this issue. 

Thanks and regards,
Mishu Agrawal

**Comment by mishuagrawal** [comment]
Hello @sonjadeissenboeck ,

Please know that the document has been updated and is now reflecting the change. You can check the documentation here:

https://ui5.sap.com/1.127.0/#/topic/8eb695ac473b4ab0a726e4021ce35cf4

Please confirm if we can go ahead and close this issue.

Thanks and regards,
Mishu Agrawal
