### ISSUE TITLE
[Question] enabling-actions-added-using-extension-points -> How to set AI Icon?

### ISSUE THREAD

**Issue by HetzlerKai** [SAP-docs/sapui5#161]
### Issue description

Hi Colleagues,

It seems that custom actions, added via the extension points for the List Report, cannot be provided with an Icon, is that correct?
At least if I provide an icon property it seems to be ignored.

For AI related Actions the icon sap-icon://ai shall be used, how can this be achieved via extension points?

Thanks and Kind Regards
Kai

<img width="180" alt="2024-09-27_16-45-57" src="https://github.com/user-attachments/assets/2d098bd4-6f9e-4a61-9630-b6e51cc86a49">

### Feedback Type (Optional)

None

**Comment by KvM2** [comment]
Hi @HetzlerKai , thanks for your contribution! Could you tell us which page of the UI5 developer guide you are referring to? Thanks.

**Comment by HetzlerKai** [comment]
Sure!
It's the one linked below and here the topic regarding the List Report & OData V2: 

https://github.com/SAP-docs/sapui5/blob/main/docs/06_SAP_Fiori_Elements/enabling-actions-added-using-extension-points-dd78aca.md

**Comment by HetzlerKai** [comment]
Hi Divya, 
are there any updates on this?
We are coming close to DC for OP2023FPS3 and this would be an important point for us.
Thanks!

**Comment by DivyaVD** [comment]
Hello HetzlerKai, 

Sorry for the delay in my response. I will check and get back to you ASAP.

**Comment by DivyaVD** [comment]
Hello HetzlerKai, 

Thank you for being so patient. I took this issue with the concerned PO and the developer. The developer investigated the issue and informed me that V2 doesn't support an AI icon with custom actions for now. 
Once again, I appreciate your patience and understanding. Please let me know if you need any further clarification or assistance regarding this matter.

**Comment by DivyaVD** [comment]
Hi, 

I checked with the developer, and he mentioned that currently, V2 doesn't have any provision to include AI icons in the action buttons. Please let me know if you have any further questions.

**Comment by HetzlerKai** [comment]
Hi Divya, 

thanks for the support so far, we will inform our stakeholder accordingly.

Have a nice Day!
Kai

**Comment by DivyaVD** [comment]
Hi HetzlerKai, 

You're welcome! I'm glad I could help. I will also go ahead and close the GitHub issue. 
Have a great day!

**Comment by HetzlerKai** [comment]
Hi Divya,

sorry, one more question, are there plans to support this with future versions, is there an timeline for this?

Thanks and Regards
Kai
