### ISSUE TITLE
Incomplete Sentences on Language Code / Locale page

### ISSUE THREAD

**Issue by clnative** [SAP-docs/sapui5#167]
The sentences at

https://github.com/SAP-docs/sapui5/blob/6147c44b9da98d4a1a913a98e462dbc1a96c6e2b/docs/04_Essentials/identifying-the-language-code-locale-91f21f1.md?plain=1#L237

are incomplete, e.g. 

> language codes are handled by the .

and

>  If you develop your app to run in the SAP Fiori launchpad. 

is an incomplete sentence.

Could you please check what is meant in the LOIO original?

Thanks!

**Comment by KvM2** [comment]
Hi @clnative , thanks for your contribution! We'll look into it and will get back to you.

**Comment by KlattG** [comment]
This has already been spotted by another user on a different platform and will be fixed in a forthcoming release.
