### ISSUE TITLE
Support Assistant tool issue

### ISSUE THREAD

**Issue by rchandak1** [SAP-docs/sapui5#20]
Hello Team,
we are getting Support assistant high priority issue for "editable" property of sap.ui.layout.form.Form
Either setting editable property or not, still its throwing high priority issue.
As of now we have only non-editable content in our form.
The editable property of the Form is used to align the Labels and add screen reader information.
For more detail refer below screenshot.
Please guide how to resolve this issue?

![support assistant issue](https://user-images.githubusercontent.com/119996803/206091398-af0d2084-7644-4595-989c-402e21fe585d.png)

**Comment by OlMue** [comment]
Hi @rchandak1, thanks for your contribution! Since this repo is just for documentation topics, we can't help you here. I will try to find out where you can post your question to get help quickly and let you know here.

**Comment by OlMue** [comment]
Okay:

**SAPUI5**
If you're an SAPUI5 customer, please create a ticket (BCP incident) for component **CA-UI5-CMP**. You can additionally try the options listed below for OpenUI5

**OpenUI5**
If you're an OpenUI5 user, you can:
- Post your question in the [SAP Community](https://answers.sap.com/questions/ask.html?primaryTagId=500983881501772639608291559920477) (use the `SAPUI5` tag)
- Post your question on [Stackoverflow](https://stackoverflow.com/search?q=sapui5) (use the `sapui5` tag)
- Join the [OpenUI5 Slack channel (free)](https://ui5-slack-invite.cfapps.eu10.hana.ondemand.com/) and ask your question there.

I hope this helps. Best regards,
Oliver

**Comment by rchandak1** [comment]
Hello @OlMue thanks for your reply.
I will proceed further with above suggested options.

Thanks & Best regards,
Roshani
