### ISSUE TITLE
Demo Kit: image thumbnail and caption clickable but nothing happens

### ISSUE THREAD

**Issue by boghyon** [SAP-docs/sapui5#23]
1. Visit a Demo Kit documentation page that contains an image thumbnail with a caption. E.g. https://ui5.sap.com/#/topic/239b1922758645e7b451e01ded7f56bc (Scroll down to the "Additional Features in SAP Fiori Elements for OData V4" section to see them).
2. Click on "Message Popover: Chevron Navigation to Message Details" or the image thumbnail.

![Fiori elements documentation - Using Messages broken clickable thumbnail](https://user-images.githubusercontent.com/12143247/209845377-d3a5a1d3-393b-4753-b82e-ce6d925285b6.png)

Apart from nothing happening on click, the layout seems to be incorrectly rendered too.

It is also unclear where the image thumbnails actually come from. The source https://github.com/SAP-docs/sapui5/blob/b33d3c0b11a6b7f5883bf9aea8ab14ceeae051e8/docs/06_SAP_Fiori_Elements/using-messages-239b192.md has no references to the thumbnails.

**Comment by JannaLisa** [comment]
Hello @boghyon ,

thanks for spotting this. I checked the feature map, and expanding thumbnails generally works. But definitely not in this topic. I will try to correct this for the upcoming release. I'll also correct the layout.
But I don't quite understand what you mean in your last statement: "It is also unclear where the image thumbnails actually come from. The source https://github.com/SAP-docs/sapui5/blob/b33d3c0b11a6b7f5883bf9aea8ab14ceeae051e8/docs/06_SAP_Fiori_Elements/using-messages-239b192.md has no references to the thumbnails."
The topic simply wants to show that you can navigate to the details of a message from the message popover. That's what the thumbnail is showing.
The source of our documentation isn't on GitHub, but on UI5.sap.com. The topic there contains the thumbnail, GitHub apparently simply isn't displaying this one. I checked other topics such as https://github.com/SAP-docs/sapui5/blob/b33d3c0b11a6b7f5883bf9aea8ab14ceeae051e8/docs/06_SAP_Fiori_Elements/confirmation-popups-9a53662.md and the images there work fine (though they are not thumbnails).
So I hope that by updating the layout and providing the image your issue will be resolved.
Please note that the change won't become visible until the release of 1.110.

Thanks!

**Comment by JannaLisa** [comment]
Hi @boghyon ,
Just so you don't think I've forgotten this: I haven't ;-)
This is a very puzzling issue, since in our internal test system where I checked everything looks perfectly fine. Just not in the external system. So I'm creating a ticket for this now myself.
As soon as this is fixed I'll let you know.
My apologies for not being able to provide a solution yet.

**Comment by JannaLisa** [comment]
Hello @boghyon,
could you please check whether you are now able to expand the thumbnail?
(Please note that apparently, clicking on the arrow icon in the right-hand corner isn't how you open it; you need to click somewhere on the thumbnail itself (like in the middle)).
For me it works now. I checked multiple examples we use in the topic SAP Fiori Elements Feature Map (https://ui5.sap.com/#/topic/62d3f7c2a9424864921184fd6c7002eb), and all of them worked.
Could you please verify and if now hopefully everything works for you as well, close this issue?
If not, then please report back!
Thanks very much.

**Comment by boghyon** [comment]
@JannaLisa I can confirm that the thumbnails can be now expanded to a LightBox. Thanks a lot! There is one issue left I mentioned in the issue description:

> 2. Click on "Message Popover: Chevron Navigation to Message Details" <del>or the image thumbnail</del>.

When clicking on the caption "Message Popover: Chevron Navigation to Message Details" nothing happens. Maybe it's not supposed to be clickable?

**Comment by JannaLisa** [comment]
Hi @boghyon ,
what we're doing is using an attribute called 'minimized-small'. My initial assumption was that this is what's causing the title/caption to look like it's a link. But we use this attribute all over the place in the topic SAP Fiori Elements Feature Map (https://ui5.sap.com/#/topic/62d3f7c2a9424864921184fd6c7002eb) as well, and there the titles are fine.
I've now asked a colleague to investigate, let's hope he's able to come up with a solution.
I'm sorry, I'm simply stuck.
But I'll keep you posted.

**Comment by OlMue** [comment]
Hi @JannaLisa, I also can't find any difference in our CCMS between the minimized image in [https://ui5.sap.com/#/topic/239b1922758645e7b451e01ded7f56bc](https://ui5.sap.com/#/topic/239b1922758645e7b451e01ded7f56bc) and in the Feature Map ([https://ui5.sap.com/#/topic/239b1922758645e7b451e01ded7f56bc](https://ui5.sap.com/#/topic/239b1922758645e7b451e01ded7f56bc). So I tend to see this as a bug in the Demo Kit and nothing we can fix in the documentation source.

@boghyon: We will address this with the Demo Kit team and close this issue for now.
