### ISSUE TITLE
Broken Link to "SAP Annotations for OData Version 2.0"

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/sapui5#24]
The link to "SAP Annotations for OData Version 2.0" at http://scn.sap.com/docs/DOC-44986 does not work anymore. See https://github.com/SAP-docs/sapui5/blob/main/docs/06_SAP_Fiori_Elements/working-with-ui-annotations-83c89cc.md?plain=1#L66

Probably https://sap.github.io/odata-vocabularies/docs/v2-annotations.html might be the right link.

Kind regards,
Sebastian

**Comment by OlMue** [comment]
Hi  @sebastianesch, happy new year! Thanks for spotting this. We'll take a look and let you know as soon as this is resolved.

**Comment by mishuagrawal** [comment]
Hello,

Thank you for bringing this to our notice. We have updated the document with the provided correct link. It should start reflecting from the 1.110 release. Please feel free to reach out to us in case of any further concern.

**Comment by mishuagrawal** [comment]
Hello @sebastianesch, if you have any issues and concerns, please let us know. If in case this concern is now resolved, please close this issue. Thank you!
