### ISSUE TITLE
Missing documentation about the Fiori Elements Test libraries

### ISSUE THREAD

**Issue by Siolto** [SAP-docs/sapui5#3]
Hi together,

It's great to now allow the whole community to improve the documentation around SAPUI5 and I want to do my part 😃.

I would like to contribute the missing documentation for the FioriElements Test libraries V2 and V4. These have, in my opinion, never been given proper documentation or announced publicly.

For that I just started to write down the first steps for the V2 integration on a [fork](https://github.com/SAP-docs/sapui5/compare/main...Siolto:sapui5:main). Here I might need some input from you to bring this forward:

- Is it from your point of view at all wanted to add a documentation for these topics?
- Is there any technical documentation of the available functions (especially for V2) other than the [JSDoc](https://sapui5.hana.ondemand.com/test-resources/sap/suite/ui/generic/template/integration/testLibrary/ListReport/pages/actions/ListReportActions.js) documentation in the source code?

Best regards,
Simon

**Comment by KvM2** [comment]
Hello Simon, thanks for your contribution! We really appreciate your contribution and will look into this .

**Comment by je-hal** [comment]
Hi @Siolto, 

thank you for taking the initiative!

Since you already have a fork with content proposals I think it would be best to discuss these changes in a pull request instead of in this issue (unless it is too early to discuss your proposal). 

If you open a pull request, we could refer to this issue and close it as soon as the pull request is approved.
What do you think?

**Comment by Siolto** [comment]
Thanks for the answer. I can improve my fork and create a pull request.

However, before I invest any more work I would like to know if the TestLibrary V2 should be published for customers and partners at all. I know that within SAP this library has been used for a long time and internally documentation already exists, which I could reuse and improve. But if it is not wanted to publish this library I would only care about the missing documentation for the TestLibrary V4 as this is already available for customers and partners.

Best regards,
Simon

**Comment by JannaLisa** [comment]
Hi @Siolto ,
For V4, we have the following tutorial available: [https://developers.sap.com/group.fiori-elements-mockserver-opa.html](url)
Could you please check if this helps? If not, please let me know.
For V2, the colleagues are still in discussions but will get back to you.
Best regards,
JannaLisa

**Comment by Siolto** [comment]
Hi @JannaLisa,

thanks for the Input. I will then start with the V4 test library. When you have updates on the V2 part, just let me know :) 

Should we keep this issue open as long as the status with the V2 TestLibrary is unclear or should we already close this one? Both is fine for me.

Regards,
Simon

**Comment by mishuagrawal** [comment]
Hello,

I checked this concern with our development team and I was unfortunately informed that currently this activity is not planned. If in case the V2 test libraries are being published in the future, we will announce the same in our what's new.

**Comment by mishuagrawal** [comment]
Hello,
I am adding this comment on behalf of Rohith Deraje - PO for Fiori Elements LROP/ALP for Odata V2:

The existing V2 OPA test library was primarily created for internal usage. To make it available for public consumption, the current architecture would have to be changed and they have to be standardized. It involves a huge effort that is currently not planned.

As stated in my earlier comment, if the development team decides to publish this in the future, we will announce it in our what's new.

**Comment by AliMazharFioneer** [comment]
Hello,
as a Developer from a Partner Company, i was trying to find information about the V2 OPA Test library and found this issue. 
I work mainly with V2 FE Applications and it would be very helpful for us, if the Library could get published for public consumption.

**Comment by mishuagrawal** [comment]
Hello, 

As mentioned in my comment earlier, the existing V2 OPA test library was primarily created for internal usage. To make it available for public consumption, the current architecture would have to be changed and they have to be standardized. It involves a huge effort that is currently not planned.

Since this has been determined by our PO, we unfortunately cannot publish the OPA test library yet. If ever this activity is planned for the future, we will announce it in our what's new. 

For now, I kindly request you to close this issue. Thank you!

**Comment by mishuagrawal** [comment]
Hello,

We have had a look at this issue, but we cannot provide a solution in the near future for the provided reasons. We are now closing this issue. If you’d like to check in again with us at a later point in time, please comment below. We'll review it and reopen the conversation if necessary. 

Thank you!
