### ISSUE TITLE
Is the the documentation regarding Read Access Logging (RAL) support correct?

### ISSUE THREAD

**Issue by gregorwolf** [SAP-docs/sapui5#30]
Hello SAPUI5 Documentation Team,

on the documentation page [SAP Gateway Export versus Client Export](https://ui5.sap.com/#/topic/e7f52f49994347cbadde95620238f3f8) there is the statement 

> RAL is not supported because the SAP Gateway export is carried out by a server process that does not run in a specific user context.

in column "SAP Gateway" for the feature "Read Access Logging (RAL) support". I don't think that is correct as the request to SAP Gateway will still be executed in a user context. Maybe @anfisc can provide some input here.

Best Regards
Gregor

**Comment by KvM2** [comment]
Hi @gregorwolf , thanks for your contribution. We appreciate it and will look into this.

**Comment by KvM2** [comment]
We are still working on this - it will take some more time. Thanks for your patience!

**Comment by HerzogIgzorn** [comment]
Hello Gregor,

I clarified this issue with the responsible Gateway development team. You are right that this information regarding RAL and GW based export is incorrect. I already created a pull request on our internal documentation repository (#387). Unfortunately you won't see it here in the public repository until it is merged.

Regards Sebastian
