### ISSUE TITLE
"Available Themes" not discoverable via "Documentation" search field

### ISSUE THREAD

**Issue by boghyon** [SAP-docs/sapui5#35]
Following https://github.com/SAP-docs/sapui5/issues/11 up, the topic https://ui5.sap.com/#/topic/da0d2e78e5414e199507cd6365d3add2 cannot be found from the "Documentation" filter in Demo Kit. It would be better if the list is simply merged to the tables in the topic [Supported Combinations of Themes and Libraries](https://ui5.sap.com/#/topic/38ff8c27b022475a92b591bcf6262551) instead of a dedicated separate topic page for a list of themes.

**Comment by KvM2** [comment]
Hi @boghyon, Thanks for the feedback . I will check this out and adapt this .

**Comment by KvM2** [comment]
Hi @boghyon, I have changed the way this document was set up. It should be available in the Demo Kit search under _Documentation_ as of 1.112.

**Comment by boghyon** [comment]
https://people.sap.com/boghyon.hoffmann
