### ISSUE TITLE
Controller Code for Sample Input Checked does not work

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/sapui5#37]
Hi,

the sample for Input - Checked (https://ui5.sap.com/#/entity/sap.m.Input/sample/sap.m.sample.InputChecked) does not work.

In the Controller code https://ui5.sap.com/#/entity/sap.m.Input/sample/sap.m.sample.InputChecked/code/C.controller.js the function `_validateInput` needs to be corrected from:

```
_validateInput: function (oInput) {
	var sValueState = "None";
	var bValidationError = false;
	var oBinding = oInput.getBinding("value");

	try {
		oBinding.getType().validateValue(oInput.getValue());
	} catch (oException) {
		sValueState = "Error";
		bValidationError = true;
	}

	oInput.setValueState(sValueState);

	return bValidationError;
},
```

to:

```
_validateInput: function (oInput) {
	var sValueState = "None";
	var bValidationError = false;
	var oBindingInfo = oInput.getBindingInfo("value");

	try {
		oBindingInfo.type.validateValue(oInput.getValue());
	} catch (oException) {
		sValueState = "Error";
		bValidationError = true;
	}

	oInput.setValueState(sValueState);

	return bValidationError;
},
```

Kind regards,
Sebastian

**Comment by KvM2** [comment]
Hi @sebastianesch, thanks for your contribution. We appreciate it and will look into this.

**Comment by simonarangelova** [comment]
Hello,

After discussing this with the team, I have moved the issue to the OpenUI5 repository, as it is not related to documentation.

Thank you

**Comment by boghyon** [comment]
@sebastianesch Let's continue at https://github.com/SAP/openui5/issues/3693
