### ISSUE TITLE
incorrect Chinese double quotes symbol

### ISSUE THREAD

**Issue by wangdongcheng** [SAP-docs/sapui5#40]
Dear experts, 
I just noticed that here should be English quote symbols rather than Chinese symbols.
Please check.
![image](https://user-images.githubusercontent.com/44392737/218749592-7c86aea3-ede0-4062-84af-5ee77852fbe1.png)

Thanks,
Dongcheng

**Comment by OlMue** [comment]
@wangdongcheng, thanks for your contribution! We're going to look into this and get back to you.

**Comment by OlMue** [comment]
@DivyaVD, @JannaLisa, this seems to be from loio9fcea86d8ffd48459dd053eb5255a046

**Comment by DivyaVD** [comment]
Hi @wangdongcheng,
I have made the correction. It will be visible with the release 1.111. 
Thank you for spotting it.
