### ISSUE TITLE
Please add specifics about OData V4 message handling

### ISSUE THREAD

**Issue by piejanssens** [SAP-docs/sapui5#46]
docs/04_Essentials/error-warning-and-info-messages-62b1481.md

**Comment by KvM2** [comment]
Hi @piejanssens , thanks for your contribution. We appreciate it and will look into this.

**Comment by KlattG** [comment]
Hi @piejanssens , a comprehensive overhaul of the Error, Warning, and Info Messages topic is in our backlog (FIORITECHP1-17715); until now we haven't had the capacity to address this. For specifics about OData V4 server messages, see 
[Server Messages in the OData V4 Model](https://sapui5.hana.ondemand.com/#/topic/fbe1cb5613cf4a40a841750bf813238e).

**Comment by KlattG** [comment]
BLI has been created. Closing this issue.
