### ISSUE TITLE
The standard "Create Object" text is not updated after configured in i18n

### ISSUE THREAD

**Issue by melissaxd96** [SAP-docs/sapui5#57]
**Describe the bug**
Unable to update the "Create Object" button text.

**To Reproduce**

1. After implementing https://sapui5.hana.ondemand.com/sdk/#/topic/189e2d8a59f04a2693a4fde7f4a91a65 , when click on create button will display two options. "Create Object" and "Create with Filters", however after configured the key in i18n based on the documentation stated, the "Create Object" button still doesn't reflect as per the text maintained in i18n.
![image](https://github.com/SAP-docs/sapui5/assets/73872266/331d3d96-8fb2-4580-8c1b-fc7ca301837c)

![image](https://github.com/SAP-docs/sapui5/assets/73872266/d2a34cda-6bcb-4c36-8a0e-82b64325e95e)

![image](https://github.com/SAP-docs/sapui5/assets/73872266/2f557f25-f384-413d-a4fe-49ce7b3d8022)

**Expected behavior**
After configure the key in i18n, the "Create Object" text should be replaced with what is maintained in i18n.

**Actual Result**
The text is not updated
![image](https://github.com/SAP-docs/sapui5/assets/73872266/f484ea42-f43f-44ec-879a-ab67c3cbaa68)

**Logs/Console Output**
N/A, no error.

- `UI5` version: 1.111.0
- OS: Windows 10
- Browser + Version : Chrome Version 113.0.5672.127

**Comment by sumanju** [comment]
Hello All,

You have defined the i18n text in wrong place. You should maintained in ListReport i18n File. Not where you defined right now.
For any further query you can reach out to me 
suman.mandal01@sap.com

Regards,
Suman

**Comment by mishuagrawal** [comment]
Hello,

As mentioned by our dev team member Suman, the i18n text is to be maintained in the list report i18n file. Our document mentions the same in the screenshot. If this still does not resolve the concern, please feel free to write back to us and the devs and I will look into it again.

Thanks and regards,
Mishu Agrawal
