### ISSUE TITLE
[doc issue] Link on "The Share Building Block" pointing to "API Reference" returns: The requested resource was not found.

### ISSUE THREAD

**Issue by gregorwolf** [SAP-docs/sapui5#73]
### Issue description

On the page [The Share Building Block](https://ui5.sap.com/#/topic/41b02dfe1ac44d72bb766f5fc3e3d244) there is a link [API Reference](https://ui5.sap.com/#/api/sap.fe.macros.Share) that returns a page with:

"The requested resource was not found."

### Feedback Type (Optional)

linking

**Comment by simonarangelova** [comment]
Hi @gregorwolf, thanks for your contribution. We appreciate it and will look into this.

**Comment by JannaLisa** [comment]
Hello @gregorwolf ,
Could you please use the latest available version of SDK and check again?
For me, the link resolves. I tested in a lower version and there I also had the issue you described.
But the issue should no longer be there in 1.117.
Please check and let me know in case it's not working for you.
Thanks!

**Comment by JannaLisa** [comment]
Hi @gregorwolf ,
is the issue now resolved for you?
If so, please close this issue.
Thanks!

**Comment by gregorwolf** [comment]
https://people.sap.com/gregorw

**Comment by gregorwolf** [comment]
Hi @JannaLisa,

seems I missed the updates that you did during my vacation. Yes, the link is working now.

Thank you.
