### ISSUE TITLE
Issue in the generated links on the deployed version

### ISSUE THREAD

**Issue by PierreFritsch** [SAP-docs/sapui5#78]
## Issue Description

When I open the (deployed version of the) documentation page: [Extension Points for Tables](https://sapui5.hana.ondemand.com/sdk/#/topic/d525522c1bf54672ae4e02d66b38e60c.html)

and I click on the link: 

> For more information, see [Configuring Responsive Behavior of a Table](https://sapui5.hana.ondemand.com/sdk/topic/38855e06486f4910bfa6f4485f7c2bac.html).

then my browser gives me the error 404 *The requested resource is not available.*

The same issue occurs with the link:

> For more information, see [Using the Export Feature](https://sapui5.hana.ondemand.com/sdk/topic/4bab6f2043814257974b52d4dafe1dcd.html).

## Screenshots

![Screenshot 2023-09-27 at 09 19 31](https://github.com/SAP-docs/sapui5/assets/10234267/30729d18-e8d1-4451-a76e-a9653d194065)
![Screenshot 2023-09-27 at 09 19 15](https://github.com/SAP-docs/sapui5/assets/10234267/9ced2e3d-de88-4248-8095-9e3bf2aaaa3f)
![Screenshot 2023-09-27 at 09 19 40](https://github.com/SAP-docs/sapui5/assets/10234267/120d6bb6-5287-484d-b176-5c087c5815f3)

## Further information

When I open the corresponding markdown page by clicking on "Edit on GitHub", the links work properly.

https://github.com/SAP-docs/sapui5/blob/main/docs/06_SAP_Fiori_Elements/extension-points-for-tables-d525522.md

### Feedback Type (Optional)

linking

**Comment by KvM2** [comment]
Hi @PierreFritsch , thanks for your contribution and thorough look at the documentation. We appreciate it and will look into this.

**Comment by KvM2** [comment]
Hi @PierreFritsch  , I tested this in various scenarios and it works for me in Edge. Which browser are you using? Thanks for your help

**Comment by PierreFritsch** [comment]
Hi @KvM2,
Thanks for your fast reaction! I still face the issue with Safari 16.6 and Chrome 116.

**Comment by KvM2** [comment]
Thanks, @PierreFritsch . We will look into this.

**Comment by LilyanaOviPe** [comment]
Hi @PierreFritsch, 

Thanks for pointing out this issue. We've addressed it to the appropriate team. Could you please confirm that you get Error 404 only when trying to open the link in a new tab and if you click directly on the link to open it in the same window, it opens correctly.

Thanks a lot.

**Comment by PierreFritsch** [comment]
Hi @LilyanaOviPe 

The issue can be reproduced on Safari on iOS 17.0.1 when attempting to open the linked pages above directly from GitHub. No new tab needed.

**Comment by simonarangelova** [comment]
Thanks again @PierreFritsch! This will be fixed with the next version.
