### ISSUE TITLE
 [Fiori element JourneyRunner code coverage of extended view controller] 

### ISSUE THREAD

**Issue by Avinashasap** [SAP-docs/sapui5#79]
### Issue description

I have added a opaTests.qunit.html to below code but its unable to recognise the code coverage which is available on ext folder (where we have custom view and controller)

    <script src="/resources/sap/ui/qunit/qunit-coverage-istanbul.js"
    data-sap-ui-cover-only="projectui/ext"
    data-sap-ui-cover-never="../test/"></script>

### Feedback Type (Optional)

None

**Comment by KvM2** [comment]
Hi @Avinashasap , thanks for your contribution. Which documentation is affected by this issue - could you add a link? Thanks

**Comment by Avinashasap** [comment]
> Hi @Avinashasap , thanks for your contribution. Which documentation is affected by this issue - could you add a link? Thanks

This is more over question on how to Integrate the fiori elements with coverage. currently if I add qunit-coverage-istanbul.js , coverage files only shows the test files and not the custom files . 

I was referring below document

https://sapui5.hana.ondemand.com/sdk/#/topic/7ef32428dc7c4c048a8d7e8de0a556fb

**Comment by KvM2** [comment]
Hi @Avinashasap , sure, I see. Would you mind posting this somewhere else since this repository is actually related to the developer guide for UI5 ? Thank you

**Comment by Avinashasap** [comment]
sure
