### ISSUE TITLE
[doc issue] example not runnable; no manifest.json

### ISSUE THREAD

**Issue by RobertFent** [SAP-docs/sapui5#80]
### Issue description

Hello,
during implementation of the [first step of the getting started](https://github.com/SAP-docs/sapui5/blob/main/docs/03_Get-Started/step-1-ready-851bde4.md) I encountered an issue.
Running this example with the given package.json results the following error:

> Error Message:
Could not find required manifest.json for project sap-m-tutorial-quickstart-01: Could not find resource /manifest.json in project sap-m-tutorial-quickstart-01`

Serving the manifest.yaml would solve this issue :-)

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Step 1: Ready...

### Page URL on SAP Help Portal (prefilled)

https://github.com/SAP-docs/sapui5/blob/main/docs/03_Get-Started/step-1-ready-851bde4.md

**Comment by OlMue** [comment]
Hi @RobertFent, thanks for your contribution. We'll look into this and get back to you.

**Comment by flovogt** [comment]
Hi @RobertFent, thanks for opining this issue. We are already working on a fix for this in back log item CPOUI5FOUNDATION-713. I'll update this issue here when the fix is available.

**Comment by KlattG** [comment]
Quickstart tutorial has been fixed from 1.120.1 / 1.121

**Comment by RobertFent** [comment]
https://people.sap.com/robertfent
