### ISSUE TITLE
How to make Dynamic visibility of custom section in manifest.json with OData V2?

### ISSUE THREAD

**Issue by jberthe** [SAP-docs/sapui5#81]
### Issue description

Is there a way to dynamically control the visibility of a custom section, similar to custom actions using the "applicablePath" property?

### Feedback Type (Optional)

content gaps

**Comment by KvM2** [comment]
Hi @jberthe, thanks for your contribution. Can you add a link to the documentation that is affected in this issue? thanks

**Comment by jberthe** [comment]
Hi, here is the documentation (OData V2 part) : 
[Extension Points for Sections on the Object Page](https://ui5.sap.com/#/topic/92ad9968e41748aeb74971f7a08a91c8)

**Comment by KvM2** [comment]
Thanks, @jberthe! We will look into this .

**Comment by Abhishek-Anand12** [comment]
From Fe side, there is no manifest settings available for the captioned feature. However, you can set the 'visible' property of the parent/first UI5 control which is used in the extension fragment to the path which determines the visibility of the custom section and based on the control's visibility, its parent section's visibility would be changed as well.

**Comment by mishuagrawal** [comment]
Hello @jberthe, 

Our expert has provided an update for your concern. Please confirm if this resolves your concern. If not, please feel free to write back to us. 

Thanks and regards,
Mishu Agrawal

**Comment by jberthe** [comment]
The solution provided, would works for content inside the section. But it will not hide the whole section.

**Comment by Abhishek-Anand12** [comment]
> The solution provided, would works for content inside the section. But it will not hide the whole section.

Could you provide the application URL, its credentials and steps to replicate the issue. The proposed solution should have worked but if it doesn't, I could have a look.

**Comment by mishuagrawal** [comment]
Hello @jberthe,

Since this is not an issue related with our documentation I will be closing this issue. You can create a ticket regarding your concern and reach out to Abhishek using the CA-UI-ST-OP component and he will get back to you with a resolution for your concern.

If you have any concerns, please feel free to reach out to us.

Thanks and regards,
Mishu Agrawal
