### ISSUE TITLE
Small Problem with API Docu for sap.suite.ui.microchart.ColumnMicroChart 

### ISSUE THREAD

**Issue by DerGuteWolf** [SAP-docs/sapui5#86]
### Issue description

"When no custom tooltip is defined, the tooltip is generated automatically based on the logic described in [sap.ui.core.Element#getTooltip_AsString](https://ui5.sap.com/api/sap.ui.core.Element#methods/getTooltip_AsString)."

Unfortunatly there is no (longer?) description of any logic behind the link.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

sap.suite.ui.microchart.ColumnMicroChart - API Reference - Demo Kit - SAPUI5 SDK

### Page URL on SAP Help Portal (prefilled)

https://ui5.sap.com/#/api/sap.suite.ui.microchart.ColumnMicroChart%23overview

**Comment by KvM2** [comment]
Hi @DerGuteWolf , Thanks for your contribution and the observation! Since this is about the API documentation and not the developer guide, would you mind giving this feedback in a different channel, for example, the Demo Kit feedback channel? Thanks!

**Comment by DerGuteWolf** [comment]
Hi @KvM2, I was a bit unsure what to use for feedback for UI5-only API documentation. Could you elaborate a bit what you mean with "Demo Kit feedback channel"?

**Comment by KvM2** [comment]
Hi @DerGuteWolf, can you let me  know if this info helped? I will then close this issue.  Thanks

**Comment by KvM2** [comment]
Hi @DerGuteWolf,  I just checked again: the feedback icon (and then the button _Give Feedback_  rather than the survey) is fine as well. There is a field where you can enter free text and say if it is related to the current (API) page you are on, just in case you don't know this.

**Comment by KvM2** [comment]
Hi @DerGuteWolf, The link I added  was actually another one for (developer guide) documentation. My apologies. This is the one I wanted to mention in the first place: https://github.com/SAP/openui5/issues.

**Comment by KvM2** [comment]
I am closing this now since this has been open for some time and needs to be addressed in another channel , since it is about the API documentation. Let us know if you still have any feedback.
