### ISSUE TITLE
Walkthrough Step 28 not complete

### ISSUE THREAD

**Issue by thunermay** [SAP-docs/sapui5#9]
When programming the Walkthrough Step 28, there is something missing.
In the `NavigationJourney.js` there are 4 steps:
- Given: iStartMyUiComponent
- When: onTheAppPage.iPressSayHelloWithDialogButton
- Then: onTheAppPage.iShouldSeeTheHelloDialog
- Then: iTearDownMyApp
The problem is that after this there are only 2 of the 4 implemented (in `pages/App.js`)
because of this, the test does not work according to the walkthrough
Please add those two steps so that the test works
thanks

**Comment by KvM2** [comment]
Hello , thanks for your contribution! We really appreciate it and will look into this .

**Comment by KlattG** [comment]
@D065444 The test seems to run, and the assertion passes. Should we, for the sake of completeness, still add the two missing functions?

**Comment by KlattG** [comment]
The developer's guide also mentions the use of jQuery - is this still up to date?

**Comment by KlattG** [comment]
Hello @thunermay , the 2 methods you're missing in pages/App.js are provided by OPA and don't have to be implemented there. If your test is failing, the reason should be somewhere else. Therefore I'm closing this issue.

**Comment by thunermay** [comment]
https://people.sap.com/test12345678901234567890
