### ISSUE TITLE
Walkthrough Tutorial -> Step 9: Component Configuration -> webapp/Component.js: wrong bundle name

### ISSUE THREAD

**Issue by micbez** [SAP-docs/sapui5#91]
### Issue description

Hi colleagues,

I've realized small bug in _Walkthrough_ exercise -> _Step 9: Component Configuration_ -> _webapp/Component.js_.  Here is defined bundle as "**sap.ui.demo**.walkthrough.i18n.i18n", but correct name is "**ui5**.walkthrough.i18n.i18n". Please double check my finding (e.g. with bundle from previous step = _Step 8: Translatable Texts_). And thank you for correction! :)

Kind regards,
Michal

P.S. I like this Walkthrough ;)

**Comment by KlattG** [comment]
Hi @micbez , thanks for letting us know.
Issue will be fixed from 1.120.2 / 1.121
Kind regards
Günter
