### ISSUE TITLE
Missing showCurrentTimeButton & showCurrentDateButton function in Smartform Smartfields

### ISSUE THREAD

**Issue by NolpaAnna** [SAP-docs/sapui5#92]
### Issue description

In DateTimePicker it is possible to use a shortcut for navigating to the current date or time (sap.m.DateTimePicker, property: showCurrentDateButton & showCurrentTimeButton). Is it possible to use these functions in  a Smartfield?

https://experience.sap.com/fiori-design-web/datetime-picker/#today-button
![image](https://github.com/SAP-docs/sapui5/assets/150681841/a45df9af-aeb7-4ef3-840c-be65fca20949)

### Feedback Type (Optional)

examples or samples

**Comment by OlMue** [comment]
Hi @NolpaAnna, thanks for your contribution! This repo only handles issues and PRs for the existing [documentation](https://ui5.sap.com/#/topic), so we can't answer your question here. Could you please address your question here: [https://github.com/SAP/openui5/issues](https://github.com/SAP/openui5/issues). The colleagues there should be able to help you.
thanks!
