### ISSUE TITLE
Sample: Walkthrough - Step 26 - Mock Server Configuration - Issue in downloaded file "mockServer.html"

### ISSUE THREAD

**Issue by micbez** [SAP-docs/sapui5#93]
### Issue description

Hi colleagues,

during my Walkthrough exercise (Step 26) I've downloaded complete source code of this exercise. I've realized issue in downloaded file _mockServer.html_ in attribute _src_. Downloaded file contains wrong value "resources/sap-ui-core.js", but I assume the right value is "../resources/sap-ui-core.js". You can check it against source code for _mockServer.html_ displayed directly at this Walkthrough exercise. With wrong value in the code I was not able to run the exercise. 

Thank you for double checking and correction :) 

Kind regards
Michal

**Comment by OlMue** [comment]
Hi @micbez, thanks for letting us know, we'll look into this.

**Comment by KlattG** [comment]
The issue has been fixed with UI5 1.120.1
