### ISSUE TITLE
[doc issue] Missing modification in Step 4: Two-Way Data Binding for file index.html

### ISSUE THREAD

**Issue by hhelibeb** [SAP-docs/sapui5#94]
### Issue description

I discovered an omission in Tutorial Step 4: Two-Way Data Binding. There is an essential modification in the `index.html` file,  the attribute `data-sap-ui-resourceroots` , which is present in the provided code sample but not described in the tutorial text. This omission leads to exception when following the code provided in the tutorial.
There is no data-sap-ui-resourceroots in step 3,
![图片](https://github.com/SAP-docs/sapui5/assets/16676760/3ad137e5-5dbf-4859-a572-abd88394ee2a)
but we can find it in step 4,
![图片](https://github.com/SAP-docs/sapui5/assets/16676760/4bb1fea6-2a9a-4227-8e70-475a9f18e560)

Please consider updating the tutorial to include the missing modification found in the `index.html` file.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Step 4: Two-Way Data Binding

### Page URL on SAP Help Portal (prefilled)

https://sapui5.hana.ondemand.com/sdk/#/topic/c72b922fdb59422496661000165d7ff1

**Comment by KlattG** [comment]
Hi @hhelibeb , thanks for pointing this out. We agree that the description should be improved and decided to fix the issue as part of an upcoming general revision of the Data Binding tutorial and sample code.

We close this issue for the time being and let you know once we've revised the tutorial.

**Comment by KlattG** [comment]
Hi @hhelibeb , thanks again for your contribution. I just wanted to let you know that we've now revised the tutorial and fixed the issue as of UI5 1.122
