### ISSUE TITLE
Value help dropdown Query

### ISSUE THREAD

**Issue by aditisaini91** [SAP-docs/sapui5#95]
Hi,

I am implementing multivalue dropdown filter in ALP floor plan. I would like to know, if there is a possibility to show "All" in the default state in the dropdown?
In my case the dropdown is under the compact filters of Analytics List Page. I would like to display "All" in the dropdown, the first time the page is loaded.

![Screenshot 2023-11-22 at 12 12 33](https://github.com/SAP-docs/sapui5/assets/10531496/f688a5f3-1a37-4f69-8204-348d45e67d70)
I have visited : docs/06_SAP_Fiori_Elements/value-help-as-a-dropdown-list-2a0a630.md But If you could also point me to the sample code, if there is any apart from https://github.com/SAP-samples/fiori-elements-feature-showcase/tree/main.
Thanks!

**Comment by OlMue** [comment]
Hi @aditisaini91, thanks for your question. We will have a look and get back to you.

**Comment by JannaLisa** [comment]
Hi @aditisaini91 , 
Same comment as for the other issue: Could you please close it? 
Thanks.
