### ISSUE TITLE
Query regarding "Adapting the UI: Analytical List Page"

### ISSUE THREAD

**Issue by aditisaini91** [SAP-docs/sapui5#97]
Hi,

I am newbie to Fiori elements. I have been working on sing floorplan Analytics List Page wit Odatav4. I would like to customize chart toolbar. Customizations are as follows:

- Adding a download button
- Removing the showlegend & Zoom in/out button
- Remove the header title of the chart 

I did come across this documentation : https://sapui5.hana.ondemand.com/sdk/#/topic/2c5fa29df37c4d13b5142ed7b484b274.html:~:text=showChartTypeSelectionButton-,Adapting%20the%20UI%3A%20Chart,-Feature. Howvere, it says at the top that "This topic is currently only applicable to SAP Fiori elements for OData V2." .

Is there any other way to achieve the above customizations on chart tool bar in ALP on odatav4 ?

Thanks in advance!

**Comment by KvM2** [comment]
Hi @aditisaini91 , thanks for your contribution . We appreciate it and will look into this.

**Comment by JannaLisa** [comment]
Hi @aditisaini91 ,
In SAP Fiori elements for OData V4, the ALP is not a separate floorplan, but rather a 'flavor' of the list report. When application developers configure a list report template, they can decide to create the template using the 'ALP flavor'. 
So I need to ask you to please consider this in your approach.
With this in mind, could you please check the existing documentation to see if you can find the information you need?
If not, please get back to me and I'll check with our developers.
Thanks!

**Comment by aditisaini91** [comment]
Thank you for your answer @JannaLisa . I do understand that but still I could not find any documentation for chart toolbar customization on Odata v4 for the above points I mentioned.

**Comment by JannaLisa** [comment]
Hello @aditisaini91 , 
I hope you were able to get help in the SAP Community? 
If so, may I ask you to please close this issue? 
If there's no reaction from you within the next week, I'll take the liberty of doing this myself. 
Thanks!
